# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: EC-CUBE on Heroku
email: takahiro-yonei@taodrive.com
description:
baseurl: "https://taodrive.github.io/ec-cube-on-heroku"

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-26131879-4
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
